name: Deploy Dashboard to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate dashboard
        run: |
          set -e
          python3 scripts/generate_dashboard.py

      - name: Deploy to gh-pages (peaceiris)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard
