name: Deploy Dashboard to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Seed database and generate dashboard
        run: |
          set -e
          # Create a demo record for the dashboard
          python3 scripts/add_record.py --source "github-pages" --type "demo" --summary "GitHub Pages Dashboard Demo" --details "This dashboard is automatically deployed from the main branch using GitHub Actions. It demonstrates the rescue repository template functionality."
          # Add another demo record
          python3 scripts/add_record.py --source "automation" --type "ci-cd" --summary "Automated Deployment Success" --details "The CI/CD pipeline successfully builds and deploys this dashboard, showing that all scripts pass linting and the template is working correctly."
          # Generate the dashboard with demo data
          python3 scripts/generate_dashboard.py

      - name: Deploy to gh-pages (peaceiris)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard
